import { randomUUID } from 'node:crypto'
import { ResearchStore } from '@zerowallscience/research-store'
import type { PresentationRecord } from '@zerowallscience/research-store/types'

export class PresentationWorker {
  private readonly pending = new Map<string, NodeJS.Timeout>()

  constructor(private readonly store: ResearchStore, private readonly stageDelayMs = 25) {}

  recover(): PresentationRecord[] {
    const recovered: PresentationRecord[] = []
    for (const project of this.store.listProjects()) {
      for (const presentation of this.store.listPresentations(project.id)) {
        if (['outlining', 'designing', 'generating'].includes(presentation.status)) {
          recovered.push(presentation)
          this.schedule(presentation.id)
        }
      }
    }
    return recovered
  }

  generate(id: string): PresentationRecord {
    const current = this.required(id)
    const next = current.status === 'draft' || current.status === 'failed'
      ? this.store.updatePresentation(id, { status: 'outlining', error: '' })
      : current.status === 'ready'
        ? this.store.updatePresentation(id, { status: 'generating', error: '' })
        : current
    if (next.status === 'cancelled') throw new Error('A cancelled presentation cannot be generated.')
    if (next.status === 'paused') throw new Error('Resume the presentation before generating it.')
    this.schedule(id)
    return next
  }

  pause(id: string): PresentationRecord {
    this.clear(id)
    return this.store.pausePresentation(id)
  }

  resume(id: string): PresentationRecord {
    const resumed = this.store.resumePresentation(id)
    this.schedule(id)
    return resumed
  }

  cancel(id: string): PresentationRecord {
    this.clear(id)
    return this.store.updatePresentation(id, { status: 'cancelled' })
  }

  dispose(): void {
    for (const timer of this.pending.values()) clearTimeout(timer)
    this.pending.clear()
  }

  private schedule(id: string): void {
    this.clear(id)
    const timer = setTimeout(() => { void this.advance(id) }, this.stageDelayMs)
    timer.unref()
    this.pending.set(id, timer)
  }

  private async advance(id: string): Promise<void> {
    this.pending.delete(id)
    const current = this.required(id)
    try {
      if (current.status === 'outlining') {
        const outline = current.outline.length > 0 ? current.outline : [{ title: current.title, points: ['Research objective', 'Methods and evidence', 'Conclusions'] }]
        this.store.updatePresentation(id, { status: 'designing', outline })
        this.schedule(id)
      } else if (current.status === 'designing') {
        const slides = current.outline.map((section, index) => ({
          id: randomUUID(), title: section.title, body: section.points.map(point => `- ${point}`).join('\n'),
          ...(index === current.outline.length - 1 ? { notes: 'Generated by ZeroWall Science from the persisted outline.' } : {}),
          assetUris: current.assets.filter((_, assetIndex) => assetIndex % Math.max(1, current.outline.length) === index).map(asset => asset.uri),
        }))
        this.store.updatePresentation(id, { status: 'generating', slides })
        this.schedule(id)
      } else if (current.status === 'generating') {
        this.store.updatePresentation(id, { status: 'ready' })
      }
    } catch (error) {
      const latest = this.required(id)
      if (latest.status !== 'cancelled') this.store.updatePresentation(id, { status: 'failed', error: error instanceof Error ? error.message : String(error) })
    }
  }

  private clear(id: string): void {
    const timer = this.pending.get(id)
    if (timer !== undefined) clearTimeout(timer)
    this.pending.delete(id)
  }

  private required(id: string): PresentationRecord {
    const presentation = this.store.getPresentation(id)
    if (presentation === undefined) throw new Error(`Presentation was not found: ${id}`)
    return presentation
  }
}
