/**
 * Host typert artifact: discovered automatically by @deepseek-ai/dsh-typert-loader
 * through the package's "./typert" export and registered into ctx.typert, which
 * the typert gateway consults for strict dispatch codecs.
 */
import { DESCRIPTORS } from "./descriptors.js";
import { sshErrorSchema } from "./schemas.js";

export const TYPERT = {
  package: "dsh-ssh-ops",
  face: "host",
  schemas: [
    // 0.1.6-alpha.2 loader requires create(); alpha.1 registry reads .schema — ship both.
    { name: "sshError", schema: sshErrorSchema, create: () => sshErrorSchema }
  ],
  invocations: DESCRIPTORS,
  model: {
    events: [],
    objects: [],
    services: [
      {
        description: "SSH ops sessions for the Web UI: connect to remote hosts, open PTY shells, stream input and output, resize, and disconnect. Backed by ssh2 in the host process.",
        summary: "SSH remote sessions backed by ssh2.",
        tags: [],
        jsDoc: "/**\n * SSH remote terminal sessions for the Web UI.\n */",
        key: "sshOps",
        exportName: "SshOpsService",
        members: [
          { kind: "method", name: "list", signature: "async list(request: SshListRequest): Promise<SshListResult>" },
          { kind: "method", name: "connect", signature: "async connect(request: SshConnectRequest): Promise<SshConnectResult>" },
          { kind: "method", name: "credentialList", signature: "async credentialList(request: SshCredentialListRequest): Promise<SshCredentialListResult>" },
          { kind: "method", name: "credentialSave", signature: "async credentialSave(request: SshCredentialSaveRequest): Promise<SshCredentialSaveResult>" },
          { kind: "method", name: "credentialDelete", signature: "async credentialDelete(request: SshCredentialDeleteRequest): Promise<SshCredentialDeleteResult>" },
          { kind: "method", name: "profileList", signature: "async profileList(request: SshProfileListRequest): Promise<SshProfileListResult>" },
          { kind: "method", name: "profileSave", signature: "async profileSave(request: SshProfileSaveRequest): Promise<SshProfileSaveResult>" },
          { kind: "method", name: "profileDelete", signature: "async profileDelete(request: SshProfileDeleteRequest): Promise<SshProfileDeleteResult>" },
          { kind: "method", name: "profileConnect", signature: "async profileConnect(request: SshProfileConnectRequest): Promise<SshProfileConnectResult>" },
          { kind: "method", name: "profileDisconnect", signature: "async profileDisconnect(request: SshProfileDisconnectRequest): Promise<SshProfileDisconnectResult>" },
          { kind: "method", name: "cancelProfileConnect", signature: "async cancelProfileConnect(request: SshCancelProfileConnectRequest): Promise<SshCancelProfileConnectResult>" },
          { kind: "method", name: "groupList", signature: "async groupList(request: SshGroupListRequest): Promise<SshGroupListResult>" },
          { kind: "method", name: "groupSave", signature: "async groupSave(request: SshGroupSaveRequest): Promise<SshGroupSaveResult>" },
          { kind: "method", name: "groupDelete", signature: "async groupDelete(request: SshGroupDeleteRequest): Promise<SshGroupDeleteResult>" },
          { kind: "method", name: "selectConnection", signature: "async selectConnection(request: SshSelectConnectionRequest): Promise<SshSelectConnectionResult>" },
          { kind: "method", name: "agentSettingsGet", signature: "async agentSettingsGet(request: SshAgentSettingsGetRequest): Promise<SshAgentSettingsResult>" },
          { kind: "method", name: "agentSettingsSave", signature: "async agentSettingsSave(request: SshAgentSettingsSaveRequest): Promise<SshAgentSettingsResult>" },
          { kind: "method", name: "languageGet", signature: "async languageGet(request: SshLanguageGetRequest): Promise<SshLanguageResult>" },
          { kind: "method", name: "languageSave", signature: "async languageSave(request: SshLanguageSaveRequest): Promise<SshLanguageResult>" },
          { kind: "method", name: "openSession", signature: "async openSession(request: SshOpenSessionRequest): Promise<SshOpenSessionResult>" },
          { kind: "method", name: "listTerminalContexts", signature: "listTerminalContexts(request: SshTerminalContextListRequest): Promise<SshTerminalContextListResult>" },
          { kind: "method", name: "readTerminalContext", signature: "readTerminalContext(request: SshTerminalContextReadRequest): Promise<SshTerminalContextReadResult>" },
          { kind: "method", name: "write", signature: "async write(request: SshWriteRequest): Promise<SshWriteResult>" },
          { kind: "method", name: "pendingConfirmationList", signature: "async pendingConfirmationList(request: PendingConfirmationListRequest): Promise<PendingConfirmationListResult>" },
          { kind: "method", name: "pendingConfirmationApprove", signature: "async pendingConfirmationApprove(request: PendingConfirmationActionRequest): Promise<PendingConfirmationApproveResult>" },
          { kind: "method", name: "pendingConfirmationCancel", signature: "async pendingConfirmationCancel(request: PendingConfirmationActionRequest): Promise<PendingConfirmationCancelResult>" },
          { kind: "method", name: "read", signature: "async read(request: SshReadRequest): Promise<SshReadResult>" },
          { kind: "method", name: "changeDirectory", signature: "changeDirectory(request: SshChangeDirectoryRequest): Promise<SshWriteResult>" },
          { kind: "method", name: "enableShellIntegration", signature: "async enableShellIntegration(request: EnableShellIntegrationRequest): Promise<EnableShellIntegrationResult>" },
          { kind: "method", name: "terminalStream", signature: "async *terminalStream(request: SshTerminalStreamRequest, signal?: AbortSignal): AsyncGenerator<SshReadResult>" },
          { kind: "method", name: "resize", signature: "async resize(request: SshResizeRequest): Promise<SshResizeResult>" },
          { kind: "method", name: "closeSession", signature: "async closeSession(request: SshCloseSessionRequest): Promise<SshCloseSessionResult>" },
          { kind: "method", name: "disconnect", signature: "async disconnect(request: SshDisconnectRequest): Promise<SshDisconnectResult>" },
          { kind: "method", name: "sftpList", signature: "async sftpList(request: SftpListRequest): Promise<SftpListResult>" },
          { kind: "method", name: "sftpStat", signature: "async sftpStat(request: SftpStatRequest): Promise<SftpStatResult>" },
          { kind: "method", name: "sftpReadFile", signature: "async sftpReadFile(request: SftpReadRequest): Promise<SftpReadResult>" },
          { kind: "method", name: "sftpWriteFile", signature: "async sftpWriteFile(request: SftpWriteRequest): Promise<SftpWriteResult>" },
          { kind: "method", name: "scpReadFile", signature: "async scpReadFile(request: ScpReadRequest): Promise<ScpReadResult>" },
          { kind: "method", name: "scpWriteFile", signature: "async scpWriteFile(request: ScpWriteRequest): Promise<ScpWriteResult>" },
          { kind: "method", name: "sftpMkdir", signature: "async sftpMkdir(request: SftpMkdirRequest): Promise<SftpMkdirResult>" },
          { kind: "method", name: "sftpDelete", signature: "async sftpDelete(request: SftpDeleteRequest): Promise<SftpDeleteResult>" },
          { kind: "method", name: "sftpRename", signature: "async sftpRename(request: SftpRenameRequest): Promise<SftpRenameResult>" },
          { kind: "method", name: "sftpUploadDir", signature: "async sftpUploadDir(request: SftpUploadDirRequest): Promise<SftpTransferDirResult>" },
          { kind: "method", name: "sftpDownloadDir", signature: "async sftpDownloadDir(request: SftpDownloadDirRequest): Promise<SftpTransferDirResult>" },
          { kind: "method", name: "tunnelStartLocal", signature: "async tunnelStartLocal(request: TunnelStartLocalRequest): Promise<TunnelStartLocalResult>" },
          { kind: "method", name: "tunnelStartRemote", signature: "async tunnelStartRemote(request: TunnelStartRemoteRequest): Promise<TunnelStartRemoteResult>" },
          { kind: "method", name: "tunnelStartDynamic", signature: "async tunnelStartDynamic(request: TunnelStartDynamicRequest): Promise<TunnelStartDynamicResult>" },
          { kind: "method", name: "tunnelStop", signature: "async tunnelStop(request: TunnelStopRequest): Promise<TunnelStopResult>" },
          { kind: "method", name: "tunnelList", signature: "async tunnelList(request: TunnelListRequest): Promise<TunnelListResult>" },
          { kind: "method", name: "sessionLogList", signature: "async sessionLogList(request: SessionLogListRequest): Promise<SessionLogListResult>" },
          { kind: "method", name: "sessionLogRead", signature: "async sessionLogRead(request: SessionLogReadRequest): Promise<SessionLogReadResult>" },
          { kind: "method", name: "sessionLogSearch", signature: "async sessionLogSearch(request: SessionLogSearchRequest): Promise<SessionLogSearchResult>" },
          { kind: "method", name: "sessionLogDelete", signature: "async sessionLogDelete(request: SessionLogDeleteRequest): Promise<SessionLogDeleteResult>" },
          { kind: "method", name: "listKnownHosts", signature: "listKnownHosts(request: ListKnownHostsRequest): Promise<ListKnownHostsResult>" },
          { kind: "method", name: "forgetHostKey", signature: "async forgetHostKey(request: ForgetHostKeyRequest): Promise<ForgetHostKeyResult>" },
          { kind: "method", name: "batchPlan", signature: "batchPlan(request: BatchPlanRequest): Promise<BatchPlanResult>" },
          { kind: "method", name: "batchTaskList", signature: "batchTaskList(request: BatchTaskListRequest): Promise<BatchTaskListResult>" },
          { kind: "method", name: "batchRun", signature: "async batchRun(request: BatchRunRequest): Promise<BatchRunResult>" },
          { kind: "method", name: "batchCancel", signature: "async batchCancel(request: BatchCancelRequest): Promise<BatchCancelResult>" },
          { kind: "method", name: "dbConnect", signature: "async dbConnect(request: DbConnectRequest): Promise<DbConnectResult>" },
          { kind: "method", name: "dbListConnections", signature: "async dbListConnections(request: DbListConnectionsRequest): Promise<DbListConnectionsResult>" },
          { kind: "method", name: "dbQuery", signature: "async dbQuery(request: DbQueryRequest): Promise<DbQueryResult>" },
          { kind: "method", name: "dbExecute", signature: "async dbExecute(request: DbExecuteRequest): Promise<DbExecuteResult>" },
          { kind: "method", name: "dbExport", signature: "async dbExport(request: DbExportRequest): Promise<DbExportResult>" },
          { kind: "method", name: "dbListTables", signature: "async dbListTables(request: DbListTablesRequest): Promise<DbListTablesResult>" },
          { kind: "method", name: "dbDescribeTable", signature: "async dbDescribeTable(request: DbDescribeTableRequest): Promise<DbDescribeTableResult>" },
          { kind: "method", name: "dbPreview", signature: "async dbPreview(request: DbPreviewRequest): Promise<DbPreviewResult>" },
          { kind: "method", name: "dbExplain", signature: "async dbExplain(request: DbExplainRequest): Promise<DbExplainResult>" },
          { kind: "method", name: "dbTxBegin", signature: "async dbTxBegin(request: DbTxBeginRequest): Promise<DbTxBeginResult>" },
          { kind: "method", name: "dbTxExecute", signature: "async dbTxExecute(request: DbTxExecuteRequest): Promise<DbTxExecuteResult>" },
          { kind: "method", name: "dbTxCommit", signature: "async dbTxCommit(request: DbTxCommitRequest): Promise<DbTxCommitResult>" },
          { kind: "method", name: "dbTxRollback", signature: "async dbTxRollback(request: DbTxRollbackRequest): Promise<DbTxRollbackResult>" },
          { kind: "method", name: "dbRun", signature: "async dbRun(request: DbRunRequest): Promise<DbRunResult>" },
          { kind: "method", name: "dbDisconnect", signature: "async dbDisconnect(request: DbDisconnectRequest): Promise<DbDisconnectResult>" },
          { kind: "method", name: "dbProfileList", signature: "async dbProfileList(request: DbProfileListRequest): Promise<DbProfileListResult>" },
          { kind: "method", name: "dbProfileSave", signature: "async dbProfileSave(request: DbProfileSaveRequest): Promise<DbProfileSaveResult>" },
          { kind: "method", name: "dbProfileDelete", signature: "async dbProfileDelete(request: DbProfileDeleteRequest): Promise<DbProfileDeleteResult>" },
          { kind: "method", name: "dbProfileConnect", signature: "async dbProfileConnect(request: DbProfileConnectRequest): Promise<DbProfileConnectResult>" }
        ],
        types: [
          { name: "SshListRequest", declaration: "export interface SshListRequest {}" },
          { name: "SshListResult", declaration: "export type SshListResult = SshResult<{ connections: Array<SshConnectionInfo & { agentSession?: boolean; agentRevealId?: string }>; activeConnectionId: string | null; resources?: SshSavedResourceInfo[] }>;" },
          { name: "SshSavedResourceInfo", declaration: "export interface SshSavedResourceInfo { readonly profileId: string; readonly name: string; readonly host: string; readonly port: number; readonly username: string; readonly connected: boolean; }" },
          { name: "SshAgentSettingsGetRequest", declaration: "export interface SshAgentSettingsGetRequest {}" },
          { name: "SshAgentSettingsSaveRequest", declaration: "export interface SshAgentSettingsSaveRequest { readonly agentAutoConnect: boolean; }" },
          { name: "SshAgentSettingsResult", declaration: "export type SshAgentSettingsResult = SshResult<{ agentAutoConnect: boolean }>;" },
          { name: "SshLanguageGetRequest", declaration: "export interface SshLanguageGetRequest {}" },
          { name: "SshLanguageSaveRequest", declaration: "export interface SshLanguageSaveRequest { readonly language: \"zh\" | \"en\"; }" },
          { name: "SshLanguageResult", declaration: "export type SshLanguageResult = SshResult<{ language: \"zh\" | \"en\" | null; autoApplySystemLanguage: boolean }>;" },
          { name: "SshConnectRequest", declaration: "export interface SshConnectRequest { readonly host: string; readonly port?: number; readonly username: string; readonly auth?: SshAuth; readonly credentialId?: string; readonly readyTimeout?: number; readonly name?: string; }" },
          { name: "SshConnectResult", declaration: "export type SshConnectResult = SshResult<{ connectionId: string; name?: string; host: string; port: number; username: string }>;" },
          { name: "SshCredentialListRequest", declaration: "export interface SshCredentialListRequest {}" },
          { name: "SshCredentialListResult", declaration: "export type SshCredentialListResult = SshResult<{ credentials: SshCredentialInfo[] }>;" },
          { name: "SshCredentialSaveRequest", declaration: "export interface SshCredentialSaveRequest { readonly credentialId?: string; readonly name: string; readonly authKind: 'password' | 'key'; }" },
          { name: "SshCredentialSaveResult", declaration: "export type SshCredentialSaveResult = SshResult<{ credential: SshCredentialInfo; credentialRefs: SshCredentialRefs }>;" },
          { name: "SshCredentialDeleteRequest", declaration: "export interface SshCredentialDeleteRequest { readonly credentialId: string; }" },
          { name: "SshCredentialDeleteResult", declaration: "export type SshCredentialDeleteResult = SshResult<{ deleted: boolean }>;" },
          { name: "SshCredentialInfo", declaration: "export interface SshCredentialInfo { readonly credentialId: string; readonly name: string; readonly authKind: 'password' | 'key'; readonly credentialConfigured: boolean; readonly passphraseConfigured: boolean; readonly secondaryConfigured: boolean; }" },
          { name: "SshProfileListRequest", declaration: "export interface SshProfileListRequest {}" },
          { name: "SshProfileListResult", declaration: "export type SshProfileListResult = SshResult<{ profiles: SshProfileInfo[] }>;" },
          { name: "SshProfileSaveRequest", declaration: "export interface SshProfileSaveRequest { readonly profileId?: string; readonly name: string; readonly host: string; readonly port?: number; readonly username: string; readonly authKind: 'password' | 'key'; readonly groupId?: string | null; }" },
          { name: "SshProfileSaveResult", declaration: "export type SshProfileSaveResult = SshResult<{ profile: SshProfileInfo; credentialRefs: SshCredentialRefs }>;" },
          { name: "SshProfileDeleteRequest", declaration: "export interface SshProfileDeleteRequest { readonly profileId: string; }" },
          { name: "SshProfileDeleteResult", declaration: "export type SshProfileDeleteResult = SshResult<{ deleted: boolean }>;" },
          { name: "SshProfileConnectRequest", declaration: "export interface SshProfileConnectRequest { readonly profileId: string; }" },
          { name: "SshProfileConnectResult", declaration: "export type SshProfileConnectResult = SshConnectResult;" },
          { name: "SshGroupListRequest", declaration: "export interface SshGroupListRequest {}" },
          { name: "SshGroupListResult", declaration: "export type SshGroupListResult = SshResult<{ groups: SshGroupInfo[] }>;" },
          { name: "SshGroupSaveRequest", declaration: "export interface SshGroupSaveRequest { readonly groupId?: string; readonly name: string; }" },
          { name: "SshGroupSaveResult", declaration: "export type SshGroupSaveResult = SshResult<{ group: SshGroupInfo }>;" },
          { name: "SshGroupDeleteRequest", declaration: "export interface SshGroupDeleteRequest { readonly groupId: string; }" },
          { name: "SshGroupDeleteResult", declaration: "export type SshGroupDeleteResult = SshResult<{ deleted: boolean; movedProfiles: number }>;" },
          { name: "SshProfileInfo", declaration: "export interface SshProfileInfo { readonly profileId: string; readonly groupId: string | null; readonly groupName: string | null; readonly name: string; readonly host: string; readonly port: number; readonly username: string; readonly authKind: 'password' | 'key'; readonly credentialConfigured: boolean; readonly passphraseConfigured: boolean; readonly secondaryConfigured: boolean; readonly connected: boolean; }" },
          { name: "SshCredentialRefs", declaration: "export interface SshCredentialRefs { readonly password: string; readonly privateKey: string; readonly passphrase: string; }" },
          { name: "SshGroupInfo", declaration: "export interface SshGroupInfo { readonly groupId: string; readonly name: string; readonly profileCount: number; }" },
          { name: "SshSelectConnectionRequest", declaration: "export interface SshSelectConnectionRequest { readonly connectionId: string; }" },
          { name: "SshSelectConnectionResult", declaration: "export type SshSelectConnectionResult = SshResult<{ activeConnectionId: string | null }>;" },
          { name: "SshOpenSessionRequest", declaration: "export interface SshOpenSessionRequest { readonly connectionId: string; readonly cols?: number; readonly rows?: number; readonly openedBy?: 'panel' | 'agent'; }" },
          { name: "SshOpenSessionResult", declaration: "export type SshOpenSessionResult = SshResult<SshSessionInfo>;" },
          { name: "SshTerminalContextListRequest", declaration: "export interface SshTerminalContextListRequest {}" },
          { name: "SshTerminalContextListResult", declaration: "export type SshTerminalContextListResult = SshResult<{ sessions: SshTerminalContextSession[] }>;" },
          { name: "SshTerminalContextReadRequest", declaration: "export interface SshTerminalContextReadRequest { readonly sessionId: string; readonly after?: number; readonly maxBytes?: number; }" },
          { name: "SshTerminalContextReadResult", declaration: "export type SshTerminalContextReadResult = SshResult<{ sessionId: string; data: string; historyStart: number; historyEnd: number; offset: number; nextOffset: number; wasClamped: boolean; hasMore: boolean; alive: boolean; exit: SshExit | null; redacted: boolean; shell: { atPrompt: boolean; lastExitCode: number | null; cwd: string | null; lastCommandAt: string | null; commands: number } | null }>;" },
          { name: "SshTerminalContextSession", declaration: "export interface SshTerminalContextSession { readonly sessionId: string; readonly connectionId: string; readonly name?: string; readonly host: string; readonly port: number; readonly openedAt: string; readonly openedBy: 'panel' | 'agent'; readonly alive: boolean; readonly historyStart: number; readonly historyEnd: number; }" },
          { name: "SshWriteRequest", declaration: "export interface SshWriteRequest { readonly sessionId: string; readonly data: string; }" },
          { name: "SshWriteResult", declaration: "export type SshWriteResult = SshResult<{ written: number }>;" },
          { name: "PendingConfirmationListRequest", declaration: "export interface PendingConfirmationListRequest {}" },
          { name: "PendingConfirmationListResult", declaration: "export type PendingConfirmationListResult = SshResult<{ confirmations: PendingConfirmation[] }>;" },
          { name: "PendingConfirmationActionRequest", declaration: "export interface PendingConfirmationActionRequest { readonly confirmationId: string; }" },
          { name: "PendingConfirmationApproveResult", declaration: "export type PendingConfirmationApproveResult = SshResult<{ executed: true }>;" },
          { name: "PendingConfirmationCancelResult", declaration: "export type PendingConfirmationCancelResult = SshResult<{ cancelled: true }>;" },
          { name: "PendingConfirmation", declaration: "export interface PendingConfirmation { readonly confirmationId: string; readonly connectionId: string; readonly sessionId: string; readonly name?: string; readonly host: string; readonly command: string; readonly reason: string; readonly createdAt: string; readonly prefilled: boolean; }" },
          { name: "SshReadRequest", declaration: "export interface SshReadRequest { readonly sessionId: string; readonly timeoutMs?: number; readonly after?: number; }" },
          { name: "SshTerminalStreamRequest", declaration: "export interface SshTerminalStreamRequest { readonly sessionId: string; readonly after?: number; }" },
          { name: "SshChangeDirectoryRequest", declaration: "export interface SshChangeDirectoryRequest { readonly sessionId: string; readonly path: string; }" },
          { name: "SshReadResult", declaration: "export type SshReadResult = SshResult<{ data: string; startOffset?: number; offset?: number; exit: SshExit | null }>;" },
          { name: "SshResizeRequest", declaration: "export interface SshResizeRequest { readonly sessionId: string; readonly cols: number; readonly rows: number; }" },
          { name: "SshResizeResult", declaration: "export type SshResizeResult = SshResult<{ cols: number; rows: number }>;" },
          { name: "SshCloseSessionRequest", declaration: "export interface SshCloseSessionRequest { readonly sessionId: string; }" },
          { name: "SshCloseSessionResult", declaration: "export type SshCloseSessionResult = SshResult<{ closed: boolean }>;" },
          { name: "SshDisconnectRequest", declaration: "export interface SshDisconnectRequest { readonly connectionId: string; }" },
          { name: "SshDisconnectResult", declaration: "export type SshDisconnectResult = SshResult<{ disconnected: boolean }>;" },
          { name: "SftpListRequest", declaration: "export interface SftpListRequest { readonly connectionId?: string; readonly path?: string; }" },
          { name: "SftpListResult", declaration: "export type SftpListResult = SshResult<{ path: string; entries: SftpEntry[] }>;" },
          { name: "SftpStatRequest", declaration: "export interface SftpStatRequest { readonly connectionId?: string; readonly path: string; }" },
          { name: "SftpStatResult", declaration: "export type SftpStatResult = SshResult<SftpEntry & { path: string }>;" },
          { name: "SftpReadRequest", declaration: "export interface SftpReadRequest { readonly connectionId?: string; readonly path: string; readonly maxBytes?: number; }" },
          { name: "SftpReadResult", declaration: "export type SftpReadResult = SshResult<{ path: string; data: string; truncated: boolean; bytes: number }>;" },
          { name: "SftpWriteRequest", declaration: "export interface SftpWriteRequest { readonly connectionId?: string; readonly path: string; readonly data: string; }" },
          { name: "SftpWriteResult", declaration: "export type SftpWriteResult = SshResult<{ path: string; bytes: number }>;" },
          { name: "ScpReadRequest", declaration: "export interface ScpReadRequest { readonly connectionId?: string; readonly path: string; readonly maxBytes?: number; }" },
          { name: "ScpReadResult", declaration: "export type ScpReadResult = SshResult<{ path: string; data: string; truncated: boolean; bytes: number }>;" },
          { name: "ScpWriteRequest", declaration: "export interface ScpWriteRequest { readonly connectionId?: string; readonly path: string; readonly data: string; }" },
          { name: "ScpWriteResult", declaration: "export type ScpWriteResult = SshResult<{ path: string; bytes: number }>;" },
          { name: "SftpMkdirRequest", declaration: "export interface SftpMkdirRequest { readonly connectionId?: string; readonly path: string; }" },
          { name: "SftpMkdirResult", declaration: "export type SftpMkdirResult = SshResult<{ path: string }>;" },
          { name: "SftpDeleteRequest", declaration: "export interface SftpDeleteRequest { readonly connectionId?: string; readonly path: string; }" },
          { name: "SftpDeleteResult", declaration: "export type SftpDeleteResult = SshResult<{ path: string; isDirectory: boolean }>;" },
          { name: "SftpRenameRequest", declaration: "export interface SftpRenameRequest { readonly connectionId?: string; readonly from: string; readonly to: string; }" },
          { name: "SftpRenameResult", declaration: "export type SftpRenameResult = SshResult<{ from: string; to: string }>;" },
          { name: "SftpUploadDirRequest", declaration: "export interface SftpUploadDirRequest { readonly connectionId?: string; readonly localPath: string; readonly remotePath: string; }" },
          { name: "SftpDownloadDirRequest", declaration: "export interface SftpDownloadDirRequest { readonly connectionId?: string; readonly remotePath: string; readonly localPath: string; }" },
          { name: "SftpTransferDirResult", declaration: "export type SftpTransferDirResult = SshResult<{ source: string; target: string; directories: number; files: number; bytes: number; failed: Array<{ path: string; error: string }>; }>;" },
          { name: "SftpEntry", declaration: "export interface SftpEntry { readonly name: string; readonly isDirectory: boolean; readonly size: number; readonly mtime: number; readonly mode: number; }" },
          { name: "TunnelStartLocalRequest", declaration: "export interface TunnelStartLocalRequest { readonly connectionId?: string; readonly bindAddr?: string; readonly bindPort?: number; readonly remoteHost: string; readonly remotePort: number; }" },
          { name: "TunnelStartLocalResult", declaration: "export type TunnelStartLocalResult = SshResult<{ tunnelId: string; kind: 'local'; bindAddr: string; bindPort: number; remoteHost: string; remotePort: number }>;" },
          { name: "TunnelStartRemoteRequest", declaration: "export interface TunnelStartRemoteRequest { readonly connectionId?: string; readonly bindAddr?: string; readonly bindPort?: number; readonly remoteHost: string; readonly remotePort: number; readonly targetHost: string; readonly targetPort: number; }" },
          { name: "TunnelStartRemoteResult", declaration: "export type TunnelStartRemoteResult = SshResult<{ tunnelId: string; kind: 'remote'; bindAddr: string; bindPort: number; remoteHost: string; remotePort: number; targetHost: string; targetPort: number }>;" },
          { name: "TunnelStopRequest", declaration: "export interface TunnelStopRequest { readonly connectionId?: string; readonly tunnelId: string; }" },
          { name: "TunnelStopResult", declaration: "export type TunnelStopResult = SshResult<{ tunnelId: string; stopped: boolean }>;" },
          { name: "TunnelListRequest", declaration: "export interface TunnelListRequest { readonly connectionId?: string; }" },
          { name: "TunnelListResult", declaration: "export type TunnelListResult = SshResult<{ tunnels: TunnelInfo[] }>;" },
          { name: "TunnelStartDynamicRequest", declaration: "export interface TunnelStartDynamicRequest { readonly connectionId?: string; readonly bindAddr?: string; readonly bindPort?: number; }" },
          { name: "TunnelStartDynamicResult", declaration: "export type TunnelStartDynamicResult = SshResult<{ tunnelId: string; kind: 'dynamic'; bindAddr: string; bindPort: number }>;" },
          { name: "TunnelInfo", declaration: "export interface TunnelInfo { readonly tunnelId: string; readonly kind: string; readonly bindAddr: string; readonly bindPort: number; readonly remoteHost?: string; readonly remotePort?: number; readonly targetHost?: string; readonly targetPort?: number; readonly connections?: number; readonly active: boolean; }" },
          { name: "EnableShellIntegrationRequest", declaration: "export interface EnableShellIntegrationRequest { readonly sessionId: string; }" },
          { name: "EnableShellIntegrationResult", declaration: "export type EnableShellIntegrationResult = SshResult<{ sessionId: string; enabled: boolean }>;" },
          { name: "SessionLogInfo", declaration: "export interface SessionLogInfo { readonly sessionId: string; readonly connectionId: string | null; readonly name: string | null; readonly host: string | null; readonly port: number | null; readonly openedBy: string | null; readonly startedAt: string; readonly endedAt: string | null; readonly exitCode: number | null; readonly bytes: number; readonly truncated: boolean; }" },
          { name: "SessionLogListRequest", declaration: "export interface SessionLogListRequest {}" },
          { name: "SessionLogListResult", declaration: "export type SessionLogListResult = SshResult<{ enabled: boolean; logs: SessionLogInfo[] }>;" },
          { name: "SessionLogReadRequest", declaration: "export interface SessionLogReadRequest { readonly sessionId: string; readonly offset?: number; readonly maxBytes?: number; }" },
          { name: "SessionLogReadResult", declaration: "export type SessionLogReadResult = SshResult<{ sessionId: string; data: string; startOffset: number; nextOffset: number; eof: boolean; size: number }>;" },
          { name: "SessionLogSearchRequest", declaration: "export interface SessionLogSearchRequest { readonly sessionId: string; readonly query: string; readonly maxHits?: number; }" },
          { name: "SessionLogSearchResult", declaration: "export type SessionLogSearchResult = SshResult<{ sessionId: string; hits: { offset: number; line: string }[]; scannedBytes: number; stoppedEarly: boolean }>;" },
          { name: "SessionLogDeleteRequest", declaration: "export interface SessionLogDeleteRequest { readonly sessionId?: string; }" },
          { name: "SessionLogDeleteResult", declaration: "export type SessionLogDeleteResult = SshResult<{ deleted: number; remaining: number }>;" },
          { name: "BatchPlanRequest", declaration: "export interface BatchPlanRequest { readonly command: string; readonly timeoutMs?: number; }" },
          { name: "BatchTask", declaration: "export interface BatchTask { readonly batchId: string; readonly command: string; readonly timeoutMs: number; readonly dangerous: boolean; readonly reason: string | null; readonly createdAt: string; }" },
          { name: "BatchPlanResult", declaration: "export type BatchPlanResult = SshResult<{ task: BatchTask }>;" },
          { name: "BatchTaskListRequest", declaration: "export interface BatchTaskListRequest {}" },
          { name: "BatchTaskListResult", declaration: "export type BatchTaskListResult = SshResult<{ tasks: BatchTask[] }>;" },
          { name: "BatchRunRequest", declaration: "export interface BatchRunRequest { readonly batchId: string; readonly profileIds: string[]; }" },
          { name: "BatchRunResult", declaration: "export type BatchRunResult = SshResult<{ results: { profileId: string; name: string; host: string; ok: boolean; exitCode: number | null; stdout: string; stderr: string; error: string | null }[] }>;" },
          { name: "BatchCancelRequest", declaration: "export interface BatchCancelRequest { readonly batchId: string; }" },
          { name: "BatchCancelResult", declaration: "export type BatchCancelResult = SshResult<{ cancelled: boolean }>;" },
          { name: "DbPreviewRequest", declaration: "export interface DbPreviewRequest { readonly dbConnectionId: string; readonly table: string; readonly limit?: number; readonly offset?: number; readonly signal?: AbortSignal; }" },
          { name: "DbPreviewResult", declaration: "export type DbPreviewResult = SshResult<{ table: string; columns: string[]; rows: any[]; rowCount: number; truncated: boolean; limit: number; offset: number; estimatedTotal: number | null }>;" },
          { name: "DbExplainRequest", declaration: "export interface DbExplainRequest { readonly dbConnectionId: string; readonly sql: string; readonly params?: any[]; readonly signal?: AbortSignal; }" },
          { name: "DbExplainResult", declaration: "export type DbExplainResult = SshResult<{ plan: any }>;" },
          { name: "DbTxBeginRequest", declaration: "export interface DbTxBeginRequest { readonly dbConnectionId: string; readonly signal?: AbortSignal; }" },
          { name: "DbTxBeginResult", declaration: "export type DbTxBeginResult = SshResult<{ txId: string; dbConnectionId: string }>;" },
          { name: "DbTxExecuteRequest", declaration: "export interface DbTxExecuteRequest { readonly txId: string; readonly sql: string; readonly params?: any[]; readonly signal?: AbortSignal; }" },
          { name: "DbTxExecuteResult", declaration: "export type DbTxExecuteResult = SshResult<{ affectedRows: number; rowCount: number; truncated: boolean; rows: any[]; insertId?: any }>;" },
          { name: "DbTxCommitRequest", declaration: "export interface DbTxCommitRequest { readonly txId: string; readonly signal?: AbortSignal; }" },
          { name: "DbTxCommitResult", declaration: "export type DbTxCommitResult = SshResult<{ txId: string; finished: boolean; committed: boolean }>;" },
          { name: "DbTxRollbackRequest", declaration: "export interface DbTxRollbackRequest { readonly txId: string; readonly signal?: AbortSignal; }" },
          { name: "DbTxRollbackResult", declaration: "export type DbTxRollbackResult = SshResult<{ txId: string; finished: boolean; rolledBack: boolean }>;" },
          { name: "SshProfileDisconnectRequest", declaration: "export interface SshProfileDisconnectRequest { readonly profileId: string; }" },
          { name: "SshProfileDisconnectResult", declaration: "export type SshProfileDisconnectResult = SshResult<{ disconnected: number }>;" },
          { name: "SshCancelProfileConnectRequest", declaration: "export interface SshCancelProfileConnectRequest { readonly profileId?: string; }" },
          { name: "SshCancelProfileConnectResult", declaration: "export type SshCancelProfileConnectResult = SshResult<{ cancelled: number }>;" },
          { name: "KnownHostInfo", declaration: "export interface KnownHostInfo { readonly host: string; readonly port: number; readonly algorithm: string; readonly fingerprint: string; readonly firstSeenAt: string; readonly lastSeenAt: string; }" },
          { name: "ListKnownHostsRequest", declaration: "export interface ListKnownHostsRequest {}" },
          { name: "ListKnownHostsResult", declaration: "export type ListKnownHostsResult = SshResult<{ hosts: KnownHostInfo[] }>;" },
          { name: "ForgetHostKeyRequest", declaration: "export interface ForgetHostKeyRequest { readonly host: string; readonly port?: number; }" },
          { name: "ForgetHostKeyResult", declaration: "export type ForgetHostKeyResult = SshResult<{ forgotten: boolean }>;" },
          { name: "DbConnectRequest", declaration: "export interface DbConnectRequest { readonly type: 'mysql' | 'postgresql' | 'opengauss' | 'sqlite' | 'clickhouse' | 'redis' | 'mongodb'; readonly host?: string; readonly port?: number; readonly database?: string; readonly username?: string; readonly password?: string; readonly ssl?: 'disabled' | 'preferred' | 'verify'; readonly sshConnectionId?: string; readonly name?: string; readonly signal?: AbortSignal; }" },
          { name: "DbConnectResult", declaration: "export type DbConnectResult = SshResult<{ dbConnectionId: string; name: string; type: 'mysql' | 'postgresql' | 'opengauss' | 'sqlite' | 'clickhouse' | 'redis' | 'mongodb' }>;" },
          { name: "DbListConnectionsRequest", declaration: "export interface DbListConnectionsRequest { readonly signal?: AbortSignal; }" },
          { name: "DbListConnectionsResult", declaration: "export type DbListConnectionsResult = SshResult<{ connections: DbConnectionInfo[] }>;" },
          { name: "DbQueryRequest", declaration: "export interface DbQueryRequest { readonly dbConnectionId: string; readonly sql: string; readonly params?: any[]; readonly signal?: AbortSignal; }" },
          { name: "DbQueryResult", declaration: "export type DbQueryResult = SshResult<{ columns: string[]; rows: any[]; rowCount: number; truncated: boolean }>;" },
          { name: "DbExecuteRequest", declaration: "export interface DbExecuteRequest { readonly dbConnectionId: string; readonly sql: string; readonly params?: any[]; readonly signal?: AbortSignal; }" },
          { name: "DbExecuteResult", declaration: "export type DbExecuteResult = SshResult<{ affectedRows: number; insertId?: any; truncated: boolean }>;" },
          { name: "DbListTablesRequest", declaration: "export interface DbListTablesRequest { readonly dbConnectionId: string; readonly signal?: AbortSignal; }" },
          { name: "DbListTablesResult", declaration: "export type DbListTablesResult = SshResult<{ tables: string[] }>;" },
          { name: "DbDescribeTableRequest", declaration: "export interface DbDescribeTableRequest { readonly dbConnectionId: string; readonly table: string; readonly signal?: AbortSignal; }" },
          { name: "DbDescribeTableResult", declaration: "export type DbDescribeTableResult = SshResult<{ table: string; columns: DbColumn[] }>;" },
          { name: "DbRunRequest", declaration: "export interface DbRunRequest { readonly dbConnectionId: string; readonly command?: string; readonly args?: any[]; readonly collection?: string; readonly operation?: string; readonly filter?: any; readonly document?: any; readonly update?: any; readonly options?: any; readonly signal?: AbortSignal; }" },
          { name: "DbRunResult", declaration: "export type DbRunResult = SshResult<{ result: any }>;" },
          { name: "DbDisconnectRequest", declaration: "export interface DbDisconnectRequest { readonly dbConnectionId: string; readonly signal?: AbortSignal; }" },
          { name: "DbDisconnectResult", declaration: "export type DbDisconnectResult = SshResult<{ dbConnectionId: string; disconnected: boolean }>;" },
          { name: "DbExportRequest", declaration: "export interface DbExportRequest { readonly dbConnectionId: string; readonly sql: string; readonly format?: 'csv' | 'json'; readonly delimiter?: 'comma' | 'tab' | 'semicolon' | 'pipe'; readonly header?: boolean; readonly path?: string; readonly maxRows?: number; readonly params?: any[]; readonly signal?: AbortSignal; }" },
          { name: "DbExportResult", declaration: "export type DbExportResult = SshResult<{ format: 'csv' | 'json'; columns: string[]; rows: number; bytes: number; truncated: boolean; path: string | null; content?: string }>;" },
          { name: "DbConnectionInfo", declaration: "export interface DbConnectionInfo { readonly dbConnectionId: string; readonly name: string; readonly type: 'mysql' | 'postgresql' | 'opengauss' | 'sqlite' | 'clickhouse' | 'redis' | 'mongodb'; readonly host?: string; readonly port?: number; readonly database: string | null; readonly ssl: string; readonly sshConnectionId: string | null; readonly createdAt: string; }" },
          { name: "DbColumn", declaration: "export interface DbColumn { readonly name: string; readonly type: string; readonly nullable: boolean; readonly key?: string; readonly default?: any; readonly extra?: string | null; }" },
          { name: "DbProfileListRequest", declaration: "export interface DbProfileListRequest {}" },
          { name: "DbProfileListResult", declaration: "export type DbProfileListResult = SshResult<{ profiles: DbProfileInfo[] }>;" },
          { name: "DbProfileSaveRequest", declaration: "export interface DbProfileSaveRequest { readonly dbProfileId?: string; readonly name: string; readonly type: 'mysql' | 'postgresql' | 'opengauss' | 'sqlite' | 'clickhouse' | 'redis' | 'mongodb'; readonly host?: string; readonly port?: number; readonly database?: string; readonly username?: string; readonly password?: string; readonly ssl?: 'disabled' | 'preferred' | 'verify'; readonly sshProfileId?: string | null; }" },
          { name: "DbProfileSaveResult", declaration: "export type DbProfileSaveResult = SshResult<{ profile: DbProfileInfo; credentialRefs: { password: string } }>;" },
          { name: "DbProfileDeleteRequest", declaration: "export interface DbProfileDeleteRequest { readonly dbProfileId: string; }" },
          { name: "DbProfileDeleteResult", declaration: "export type DbProfileDeleteResult = SshResult<{ deleted: boolean }>;" },
          { name: "DbProfileConnectRequest", declaration: "export interface DbProfileConnectRequest { readonly dbProfileId: string; }" },
          { name: "DbProfileConnectResult", declaration: "export type DbProfileConnectResult = DbConnectResult;" },
          { name: "DbProfileInfo", declaration: "export interface DbProfileInfo { readonly dbProfileId: string; readonly name: string; readonly type: 'mysql' | 'postgresql' | 'opengauss' | 'sqlite' | 'clickhouse' | 'redis' | 'mongodb'; readonly host?: string; readonly port?: number; readonly database: string | null; readonly username: string | null; readonly ssl: string; readonly sshProfileId: string | null; readonly credentialConfigured: boolean; readonly connected: boolean; }" }
        ]
      }
    ]
  }
};

export default TYPERT;
