import { useState } from 'react'
import type { CanvasSpec } from '../shared/canvas.js'

export function CanvasControls({ spec, change, imageSources = [], refreshSources }: { spec: CanvasSpec; change: (spec: CanvasSpec) => void; imageSources?: Array<{ kind: 'asset' | 'artifact'; id: string; name: string }>; refreshSources?: () => void }): JSX.Element {
  const [selected, setSelected] = useState(0)
  const panels = [spec, ...(spec.panels ?? [])]; const index = Math.min(selected, panels.length - 1); const panel = panels[index]!
  const update = (patch: Partial<CanvasSpec>): void => {
    if (!index) change({ ...spec, ...patch })
    else change({ ...spec, panels: spec.panels!.map((p, i) => i === index - 1 ? { ...p, ...patch } : p) })
  }
  const grid = { display: 'flex', gap: 12, flexWrap: 'wrap' as const, alignItems: 'center', margin: '10px 0' }
  const add = (): void => {
    const additional = [...(spec.panels ?? []), { title: `面板 ${panels.length + 1}`, width: 640, height: 400, xLabel: 'X', yLabel: 'Y', series: [{ id: 'series-1', name: '新数据', color: '#2f6fbd', points: [] }] }]
    const cols = Math.min(spec.columns ?? 2, 3)
    change({ ...spec, panels: additional, columns: cols, width: Math.max(spec.width, cols * 480), height: Math.max(spec.height, Math.ceil((additional.length + 1) / cols) * 360) }); setSelected(panels.length)
  }
  const remove = (): void => { if (!index) return; change({ ...spec, panels: spec.panels!.filter((_, i) => i !== index - 1) }); setSelected(index - 1) }
  const reorder = (): void => {
    if (!index) return
    const plots = panels.map(({ panels: _panels, columns: _columns, ...p }) => p)
    ;[plots[index - 1], plots[index]] = [plots[index]!, plots[index - 1]!]
    change({ ...plots[0]!, width: spec.width, height: spec.height, columns: spec.columns, panels: plots.slice(1) }); setSelected(index - 1)
  }
  return <div aria-label="画布编辑器">
    <div style={grid}><label>宽度 <input aria-label="画布宽度" type="number" min={320} max={4000} value={spec.width} onChange={e => change({ ...spec, width: Number(e.target.value) })}/></label><label>高度 <input aria-label="画布高度" type="number" min={240} max={4000} value={spec.height} onChange={e => change({ ...spec, height: Number(e.target.value) })}/></label><label>列数 <select aria-label="画布列数" value={spec.columns ?? 2} onChange={e => change({ ...spec, columns: Number(e.target.value) })}>{[1, 2, 3].map(v => <option key={v} value={v}>{v}</option>)}</select></label></div>
    <div style={grid}><label>当前面板 <select aria-label="当前面板" value={index} onChange={e => setSelected(Number(e.target.value))}>{panels.map((p, i) => <option key={i} value={i}>{String.fromCharCode(65 + i)} · {p.title}</option>)}</select></label><button type="button" disabled={panels.length >= 9} onClick={add}>添加面板</button><button type="button" disabled={!index} onClick={reorder}>前移面板</button><button type="button" disabled={!index} onClick={remove}>删除当前面板</button></div>
    <div style={grid}><label>标题 <input aria-label="面板标题" value={panel.title} onChange={e => update({ title: e.target.value })}/></label><label>X 轴 <input aria-label="X 轴标签" value={panel.xLabel} onChange={e => update({ xLabel: e.target.value })}/></label><label>Y 轴 <input aria-label="Y 轴标签" value={panel.yLabel} onChange={e => update({ yLabel: e.target.value })}/></label><label><input aria-label="显示图例" type="checkbox" checked={panel.showLegend !== false} onChange={e => update({ showLegend: e.target.checked })}/>显示图例</label></div>
    <div style={grid}><label>面板类型 <select aria-label="面板类型" value={panel.image ? 'image' : 'plot'} onChange={e => update(e.target.value === 'image' ? { image: { kind: 'artifact', id: '' }, series: [], annotations: [] } : { image: undefined, series: [{ id: 'series-1', name: '新数据', color: '#2f6fbd', points: [] }] })}><option value="plot">数据图表</option><option value="image">项目图像</option></select></label></div>
    {panel.image && <div aria-label="图像面板设置"><div style={grid}><label>项目图像 <select aria-label="项目图像" value={`${panel.image.kind}:${panel.image.id}`} onChange={e => { const source = imageSources.find(s => `${s.kind}:${s.id}` === e.target.value); if (source) update({ image: { kind: source.kind, id: source.id } }) }}><option value={`${panel.image.kind}:${panel.image.id}`}>{imageSources.find(s => s.id === panel.image!.id)?.name ?? '选择项目图像'}</option>{imageSources.filter(s => s.id !== panel.image!.id).map(s => <option key={`${s.kind}:${s.id}`} value={`${s.kind}:${s.id}`}>{s.name} · {s.kind === 'asset' ? '资产' : '产物'}</option>)}</select></label><button type="button" onClick={refreshSources}>刷新图像</button><button type="button" onClick={() => update({ image: { kind: panel.image!.kind, id: panel.image!.id } })}>重新绑定原图并清除标定</button></div><details><summary>来源引用</summary><div style={grid}><label>图像来源 <select aria-label="图像来源类型" value={panel.image.kind} onChange={e => update({ image: { id: '', kind: e.target.value as 'asset' | 'artifact' } })}><option value="artifact">分析产物</option><option value="asset">数据资产</option></select></label><label>来源 ID <input aria-label="图像来源 ID" value={panel.image.id} onChange={e => update({ image: { kind: panel.image!.kind, id: e.target.value } })}/></label></div></details><label><input aria-label="显示比例尺" type="checkbox" checked={!!panel.image.scaleBar} onChange={e => update({ image: { ...panel.image!, scaleBar: undefined, ...(e.target.checked ? { scaleBar: { length: 100, unitsPerPixel: 1, unit: 'µm', calibrationSource: '' } } : {}) } })}/>显示比例尺</label>{panel.image.scaleBar && <div style={grid}>{(['length', 'unitsPerPixel', 'unit', 'calibrationSource'] as const).map((key, i) => <label key={key}>{['标尺长度', '每像素物理单位', '物理单位', '标定来源'][i]} <input aria-label={['标尺长度', '每像素物理单位', '物理单位', '标定来源'][i]} type={i < 2 ? 'number' : 'text'} value={panel.image!.scaleBar![key]} onChange={e => update({ image: { ...panel.image!, scaleBar: { ...panel.image!.scaleBar!, [key]: i < 2 ? Number(e.target.value) : e.target.value } } })}/></label>)}</div>}<p>使用本项目已登记的 PNG/JPEG/WebP；保持纵横比。比例尺必须填写原图像素标定和来源。</p></div>}
    {(['xRange', 'yRange'] as const).map((axis, i) => <div key={axis} style={grid}><span>{i ? 'Y' : 'X'} 轴范围</span><label><input aria-label={`${axis}自动`} type="checkbox" checked={!panel[axis]} onChange={e => update({ [axis]: e.target.checked ? undefined : [0, 1] })}/>自动</label>{panel[axis] && [0, 1].map(bound => <input key={bound} aria-label={`${axis}${bound ? '上限' : '下限'}`} type="number" value={panel[axis]![bound]} onChange={e => { const range: [number, number] = [...panel[axis]!]; range[bound] = Number(e.target.value); update({ [axis]: range }) }}/>)}</div>)}
    {panel.series.map((s, i) => <div key={s.id} style={grid}><label>系列 <input aria-label={`系列${i + 1}名称`} value={s.name} onChange={e => update({ series: panel.series.map((v, j) => j === i ? { ...v, name: e.target.value } : v) })}/></label><input aria-label={`系列${i + 1}颜色`} type="color" value={s.color} onChange={e => update({ series: panel.series.map((v, j) => j === i ? { ...v, color: e.target.value } : v) })}/><select aria-label={`系列${i + 1}图形`} value={s.mode ?? 'line'} onChange={e => update({ series: panel.series.map((v, j) => j === i ? { ...v, mode: e.target.value as 'line' | 'scatter' } : v) })}><option value="line">折线和点</option><option value="scatter">散点</option></select><span>{s.points.length} 个点</span></div>)}
    <p>数据图表使用独立线性坐标轴。误差线通过点的 yLow/yHigh 明确输入，并在系列 intervalLabel 标注 SD、SE 或置信区间含义；不会自动估计。图像按原始比例显示，编辑后重新预览。</p>
  </div>
}
