import { useEffect, useRef, useState } from 'react'
import type { TypertRemoteNamespaceMap } from '@deepseek-ai/dsh-typert-protocol'
import type { DataAssetRecord, ViewerSessionRecord } from '@zerowallscience/research-store/types'
import { unwrapRemoteResult } from '../../../base/src/shared/client-helpers.ts'
import type { HeAnalysis } from '../shared/he.js'
import type { ScienceViewerRequest } from '../shared/types.js'

type Remote = TypertRemoteNamespaceMap['zerowallResearch']; type HeResponse = { he?: { width: number; height: number; pages: number; format: string; notes: string[] }; analysis?: HeAnalysis; viewer?: ViewerSessionRecord; artifact?: { name: string; uri: string; checksum: string } }
export function HeViewer({ remote, sessionId }: { remote: Remote; sessionId: string }): JSX.Element {
  const [assets, setAssets] = useState<DataAssetRecord[]>([]); const [viewers, setViewers] = useState<ViewerSessionRecord[]>([]); const [assetId, setAssetId] = useState(''); const [viewer, setViewer] = useState<ViewerSessionRecord>(); const [slide, setSlide] = useState<{ width: number; height: number; pages: number; format: string; notes: string[] }>(); const [analysis, setAnalysis] = useState<HeAnalysis>(); const [region, setRegion] = useState({ x: 0, y: 0, width: 1000, height: 1000, page: 0 }); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const generation = useRef(0)
  const call = async (input: Omit<ScienceViewerRequest, 'sessionId'>): Promise<HeResponse & { assets?: DataAssetRecord[]; viewers?: ViewerSessionRecord[] }> => { const result = unwrapRemoteResult('scienceViewer', await remote.scienceViewer({ ...input, sessionId })) as unknown as { he?: HeResponse; assets?: DataAssetRecord[]; viewers?: ViewerSessionRecord[] }; return (result.he ?? result) as HeResponse & { assets?: DataAssetRecord[]; viewers?: ViewerSessionRecord[] } }
  const refresh = async (): Promise<void> => { const result = await call({ action: 'list' }); setAssets(result.assets ?? []); setViewers((result.viewers ?? []).filter(item => item.state.heTool === 'he')) }
  useEffect(() => { const current = ++generation.current; setAssets([]); setViewers([]); setViewer(undefined); setSlide(undefined); setAnalysis(undefined); setMessage(''); void refresh().catch(error => { if (current === generation.current) setMessage(String(error)) }); return () => { generation.current++ } }, [remote, sessionId])
  const run = async (input: Omit<ScienceViewerRequest, 'sessionId'>): Promise<void> => { if (busy) return; setBusy(true); setMessage(''); try { const response = await call(input); if (response.viewer) setViewer(response.viewer); if (response.he) { setSlide(response.he); setRegion(current => ({ ...current, width: Math.min(current.width, response.he!.width), height: Math.min(current.height, response.he!.height) })) } if (response.analysis) setAnalysis(response.analysis); if (response.artifact) setMessage(`已登记产物：${response.artifact.name}\n${response.artifact.uri}\nSHA-256: ${response.artifact.checksum}`); await refresh() } catch (error) { setMessage(error instanceof Error ? error.message : String(error)) } finally { setBusy(false) } }
  const update = (key: keyof typeof region, value: number) => setRegion(previous => ({ ...previous, [key]: Number.isFinite(value) ? value : 0 }))
  return <section aria-label="HE 组织切片查看与分析" style={{ border: '1px solid var(--dsw-alias-border-l1)', borderRadius: 8, padding: 14 }}><h3>HE 组织切片查看与分析</h3><p>支持 SVS/NDPI/TIFF 的受限首层解码、原图坐标 ROI 和可复核 RGB/核样本统计。当前是 CPU 启发式筛查基线，不是 StarDist 或临床诊断模型。</p><fieldset disabled={busy} style={{ border: 0, padding: 0 }}><label>切片资产 <select aria-label="HE 资产" value={assetId} onChange={event => setAssetId(event.target.value)}><option value="">选择 SVS/NDPI/TIFF</option>{assets.filter(asset => /\.(svs|ndpi|tif|tiff)$/iu.test(asset.uri)).map(asset => <option key={asset.id} value={asset.id}>{asset.name}</option>)}</select></label><button type="button" disabled={!assetId} onClick={() => void run({ action: 'he_open', assetId })}>打开切片</button><button type="button" onClick={() => void refresh()}>刷新资产</button><div role="tablist" aria-label="已保存 HE 视图" style={{ margin: '12px 0', display: 'flex', gap: 6, flexWrap: 'wrap' }}>{viewers.map(item => <button key={item.id} role="tab" type="button" aria-selected={item.id === viewer?.id} onClick={() => void run({ action: 'he_analyze', viewerId: item.id, expectedVersion: item.version, region })}>{assets.find(asset => asset.id === item.assetId)?.name ?? 'HE'} · v{item.version}</button>)}</div>{viewer && slide && <><p>{slide.width}×{slide.height} · {slide.pages} 页 · 解码格式 {slide.format}</p><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>{(['x', 'y', 'width', 'height', 'page'] as const).map(key => <label key={key}>{key} <input aria-label={`HE ${key}`} type="number" min={0} value={region[key]} onChange={event => update(key, Number(event.target.value))} /></label>)}</div><button type="button" onClick={() => void run({ action: 'he_analyze', viewerId: viewer.id, expectedVersion: viewer.version, region })}>统计 ROI</button><button type="button" onClick={() => void run({ action: 'he_export', viewerId: viewer.id, expectedVersion: viewer.version, region })}>导出并登记</button>{analysis && <div aria-label="HE 分析结果"><p>ROI {analysis.region.x},{analysis.region.y} · {analysis.region.width}×{analysis.region.height} · {analysis.pixels} 像素</p><p>平均 RGB：{analysis.meanRgb.r.toFixed(1)}, {analysis.meanRgb.g.toFixed(1)}, {analysis.meanRgb.b.toFixed(1)}</p><p>核样本启发式比例：{(analysis.nucleiLikeFraction * 100).toFixed(2)}%</p><ul>{analysis.notes.map(note => <li key={note}>{note}</li>)}</ul></div>}<ul>{slide.notes.map(note => <li key={note}>{note}</li>)}</ul></>}</fieldset>{message && <pre role="status" style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{message}</pre>}</section>
}
