// Generated by tools/plugins/generate-typert.mjs. Do not edit.
import remote0 from '@zerowallscience/plugin-account/remote'
import remote1 from '@zerowallscience/plugin-execution/remote'
import remote2 from '@zerowallscience/plugin-files/remote'
import remote3 from '@zerowallscience/plugin-mcp/remote'
import remote4 from '@zerowallscience/plugin-presentations/remote'
import remote5 from '@zerowallscience/plugin-projects/remote'
import remote6 from '@zerowallscience/plugin-publications/remote'
import remote7 from '@zerowallscience/plugin-research/remote'
import remote8 from '@zerowallscience/plugin-runs/remote'
import remote9 from '@zerowallscience/plugin-skills/remote'

export const zerowallRemoteContributions = [remote0, remote1, remote2, remote3, remote4, remote5, remote6, remote7, remote8, remote9] as const
