export interface CanvasPoint { x: number; y: number; label?: string }
export interface CanvasSeries { id: string; name: string; color: string; points: CanvasPoint[] }
export interface CanvasAnnotation { text: string; x: number; y: number; color?: string }
export interface CanvasSpec { title: string; width: number; height: number; xLabel: string; yLabel: string; series: CanvasSeries[]; annotations?: CanvasAnnotation[]; sourceAssetIds?: string[]; sourceArtifactIds?: string[] }
export interface CanvasRender { format: 'zerowall-science-canvas'; version: 1; svg: string; width: number; height: number; pointCount: number; sourceAssetIds: string[]; sourceArtifactIds: string[]; notes: string[] }

const esc = (value: string): string => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&apos;')
const finite = (value: unknown, label: string): number => { if (typeof value !== 'number' || !Number.isFinite(value)) throw new Error(`${label} must be finite.`); return value }

export function validateCanvasSpec(value: unknown): CanvasSpec {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('Canvas specification is required.')
  const input = value as Record<string, unknown>; const text = (key: string, max: number): string => { if (typeof input[key] !== 'string' || !input[key].trim() || input[key].length > max) throw new Error(`Canvas ${key} is required.`); return input[key].trim() }
  const width = finite(input.width, 'Canvas width'); const height = finite(input.height, 'Canvas height'); if (width < 320 || width > 4000 || height < 240 || height > 4000) throw new Error('Canvas dimensions must be 320–4000 by 240–4000.')
  if (!Array.isArray(input.series) || input.series.length < 1 || input.series.length > 20) throw new Error('Canvas requires 1–20 series.')
  let pointCount = 0; const ids = new Set<string>(); const series = input.series.map((raw, seriesIndex) => { if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new Error('Canvas series must be objects.'); const item = raw as Record<string, unknown>; const id = typeof item.id === 'string' && item.id.trim() ? item.id.trim() : `series-${seriesIndex + 1}`; if (ids.has(id)) throw new Error('Canvas series IDs must be unique.'); ids.add(id); const name = typeof item.name === 'string' && item.name.trim() ? item.name.trim() : id; const color = typeof item.color === 'string' && /^#[0-9a-f]{6}$/iu.test(item.color) ? item.color : '#2f6fbd'; if (!Array.isArray(item.points) || item.points.length > 100000) throw new Error('Canvas series points must be an array no longer than 100,000.'); pointCount += item.points.length; const points = item.points.map((point, index) => { if (!point || typeof point !== 'object' || Array.isArray(point)) throw new Error('Canvas point must be an object.'); const p = point as Record<string, unknown>; return { x: finite(p.x, `Canvas ${id} point ${index} x`), y: finite(p.y, `Canvas ${id} point ${index} y`), ...(typeof p.label === 'string' && p.label.length <= 200 ? { label: p.label } : {}) } })
    return { id, name, color, points }
  }); if (pointCount > 500000) throw new Error('Canvas point count exceeds the 500,000-point bound.')
  const annotations = input.annotations === undefined ? [] : !Array.isArray(input.annotations) ? (() => { throw new Error('Canvas annotations must be an array.') })() : input.annotations.map(raw => { if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new Error('Canvas annotation must be an object.'); const item = raw as Record<string, unknown>; if (typeof item.text !== 'string' || !item.text.trim() || item.text.length > 500) throw new Error('Canvas annotation text is required.'); return { text: item.text.trim(), x: finite(item.x, 'Canvas annotation x'), y: finite(item.y, 'Canvas annotation y'), ...(typeof item.color === 'string' && /^#[0-9a-f]{6}$/iu.test(item.color) ? { color: item.color } : {}) } })
  const refs = (key: 'sourceAssetIds' | 'sourceArtifactIds'): string[] => input[key] === undefined ? [] : !Array.isArray(input[key]) ? (() => { throw new Error(`Canvas ${key} must be an array.`) })() : input[key].map(value => { if (typeof value !== 'string' || !value.trim() || value.length > 200) throw new Error(`Canvas ${key} contains an invalid reference.`); return value.trim() })
  return { title: text('title', 200), width, height, xLabel: text('xLabel', 200), yLabel: text('yLabel', 200), series, annotations, sourceAssetIds: refs('sourceAssetIds'), sourceArtifactIds: refs('sourceArtifactIds') }
}

export function renderCanvas(spec: CanvasSpec): CanvasRender {
  const all = spec.series.flatMap(series => series.points); const minX = Math.min(...all.map(point => point.x)); const maxX = Math.max(...all.map(point => point.x)); const minY = Math.min(...all.map(point => point.y)); const maxY = Math.max(...all.map(point => point.y)); const xSpan = maxX === minX ? 1 : maxX - minX; const ySpan = maxY === minY ? 1 : maxY - minY; const left = 75; const top = 55; const right = 25; const bottom = 60; const plotWidth = spec.width - left - right; const plotHeight = spec.height - top - bottom; const px = (x: number): number => left + (x - minX) / xSpan * plotWidth; const py = (y: number): number => top + (maxY - y) / ySpan * plotHeight
  const lines = spec.series.map(series => { const path = series.points.map((point, index) => `${index ? 'L' : 'M'}${px(point.x).toFixed(2)},${py(point.y).toFixed(2)}`).join(' '); return `<path d="${path}" fill="none" stroke="${esc(series.color)}" stroke-width="2"/><g fill="${esc(series.color)}">${series.points.map(point => `<circle cx="${px(point.x).toFixed(2)}" cy="${py(point.y).toFixed(2)}" r="3"/>`).join('')}</g>` }).join('')
  const legend = spec.series.map((series, index) => `<g transform="translate(${left + index * 150},${spec.height - 25})"><rect width="12" height="12" fill="${esc(series.color)}"/><text x="18" y="11" font-size="12">${esc(series.name)}</text></g>`).join('')
  const labels = (spec.annotations ?? []).map(annotation => `<text x="${px(annotation.x).toFixed(2)}" y="${py(annotation.y).toFixed(2)}" fill="${esc(annotation.color ?? '#222222')}" font-size="13">${esc(annotation.text)}</text>`).join('')
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${spec.width}" height="${spec.height}" viewBox="0 0 ${spec.width} ${spec.height}"><rect width="100%" height="100%" fill="white"/><text x="${spec.width / 2}" y="28" text-anchor="middle" font-size="18" font-weight="600">${esc(spec.title)}</text><line x1="${left}" y1="${top + plotHeight}" x2="${left + plotWidth}" y2="${top + plotHeight}" stroke="#333"/><line x1="${left}" y1="${top}" x2="${left}" y2="${top + plotHeight}" stroke="#333"/><text x="${left + plotWidth / 2}" y="${spec.height - 5}" text-anchor="middle" font-size="13">${esc(spec.xLabel)}</text><text x="15" y="${top + plotHeight / 2}" transform="rotate(-90 15 ${top + plotHeight / 2})" text-anchor="middle" font-size="13">${esc(spec.yLabel)}</text>${lines}${labels}${legend}</svg>`
  return { format: 'zerowall-science-canvas', version: 1, svg, width: spec.width, height: spec.height, pointCount: all.length, sourceAssetIds: spec.sourceAssetIds ?? [], sourceArtifactIds: spec.sourceArtifactIds ?? [], notes: ['SVG coordinates and source references are deterministic from the submitted specification.', 'The canvas does not infer statistical uncertainty, significance or scientific meaning from plotted points.'] }
}
