/**
 * Contract tests for the vendored bio-tools MCP servers.
 *
 * The contracts under `contracts/` are generated by
 * `python runtime/connectors/generate_contracts.py`, which reads the shipped
 * Python in `runtime/connectors/bio-tools/lib/`. These tests therefore assert
 * two things and nothing else:
 *
 *   1. the generated contracts still agree with the implementation they were
 *      derived from (tool names, counts, packages, source files, manifests);
 *   2. the facts the implementation actually states are stated correctly
 *      (input schemas, the two structured error codes, upstream pacing).
 *
 * Anything the servers do not declare is deliberately absent from the
 * contracts, so it is asserted absent here rather than required.
 */
import { describe, it, expect } from "vitest";
import { readFileSync, existsSync, readdirSync } from "fs";
import { join } from "path";
import Ajv from "ajv";

const HERE = __dirname;
const CONTRACTS_DIR = join(HERE, "contracts");
const CONNECTORS_DIR = join(HERE, "..", "..");
const MANIFESTS_DIR = join(CONNECTORS_DIR, "manifests");
const LIB_DIR = join(CONNECTORS_DIR, "bio-tools", "lib");

interface ContractTool {
  name: string;
  description: string;
  inputSchema: {
    type: string;
    properties: Record<string, Record<string, unknown>>;
    required?: string[];
  };
  outputSchema?: Record<string, unknown>;
  returns?: string;
  upstreams?: string[];
  errorCases?: Array<{ case: string; expectedError: { error: string; message: string } }>;
}

interface Contract {
  domain: string;
  package: string;
  derivedFrom: string;
  originalConnector?: string;
  toolCount: number;
  tools: ContractTool[];
  upstreams?: Array<{ package: string; minIntervalSeconds: number; requestsPerSecond: number }>;
}

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(path, "utf-8")) as T;
}

/** The five servers that ship a hand-written `schemas.json`. */
const SCHEMA_TIER = ["biomart", "biorxiv", "chembl", "clinical-trials", "pubmed"];

/** `domains.json` is what `run_server.py` dispatches on — the real partition. */
const DOMAIN_INDEX = readJson<Record<string, string[]>>(
  join(LIB_DIR, "mcp_bio", "domains.json"),
);
const SLUGS = Object.keys(DOMAIN_INDEX).sort();

const CONTRACTS = new Map<string, Contract>(
  readdirSync(CONTRACTS_DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => [f.replace(/\.json$/, ""), readJson<Contract>(join(CONTRACTS_DIR, f))]),
);

const entries = (): Array<[string, Contract]> =>
  [...CONTRACTS.entries()].sort(([a], [b]) => a.localeCompare(b));

const allTools = (): Array<{ slug: string; tool: ContractTool; where: string }> =>
  entries().flatMap(([slug, contract]) =>
    contract.tools.map((tool) => ({ slug, tool, where: `${slug}/${tool.name}` })),
  );

describe("domain contracts", () => {
  const ajv = new Ajv({ strict: false });

  describe("coverage", () => {
    it("covers exactly the domains run_server.py can dispatch", () => {
      expect([...CONTRACTS.keys()].sort()).toEqual(SLUGS);
    });

    it("covers all 247 vendored tools", () => {
      const total = entries().reduce((sum, [, c]) => sum + c.tools.length, 0);
      expect(total).toBe(247);
      expect(SLUGS.length).toBe(23);
    });

    it("names each contract after its file and its Python package", () => {
      for (const [slug, contract] of entries()) {
        expect(contract.domain).toBe(slug);
        expect(contract.package).toBe(`mcp_${slug.replace(/-/g, "_")}`);
      }
    });

    it("points derivedFrom at a source file that exists", () => {
      for (const [slug, contract] of entries()) {
        const expected = SCHEMA_TIER.includes(slug) ? "schemas.json" : "server.py";
        expect(contract.derivedFrom).toBe(`bio-tools/lib/${contract.package}/${expected}`);
        expect(existsSync(join(CONNECTORS_DIR, contract.derivedFrom))).toBe(true);
      }
    });
  });

  describe("agreement with the implementation", () => {
    it("lists exactly the tool names domains.json lists", () => {
      for (const [slug, contract] of entries()) {
        expect(contract.tools.map((t) => t.name).sort()).toEqual([...DOMAIN_INDEX[slug]].sort());
      }
    });

    it("reports an honest toolCount with no duplicate names", () => {
      for (const [slug, contract] of entries()) {
        expect(contract.toolCount).toBe(contract.tools.length);
        const names = contract.tools.map((t) => t.name);
        expect(new Set(names).size, slug).toBe(names.length);
      }
    });

    it("agrees with the connector manifests", () => {
      for (const [slug, contract] of entries()) {
        const manifestPath = join(MANIFESTS_DIR, `${slug}.json`);
        expect(existsSync(manifestPath), manifestPath).toBe(true);
        const manifest = readJson<{ domain: string; toolCount: number; tools: Array<{ name: string }> }>(
          manifestPath,
        );
        expect(manifest.domain).toBe(slug);
        expect(manifest.toolCount).toBe(contract.toolCount);
        expect(manifest.tools.map((t) => t.name).sort()).toEqual(
          contract.tools.map((t) => t.name).sort(),
        );
      }
    });
  });

  describe("descriptions", () => {
    it("gives every tool a single-line non-empty description", () => {
      for (const { tool, where } of allTools()) {
        expect(tool.description.trim(), where).not.toBe("");
        expect(tool.description, where).not.toContain("\n");
      }
    });
  });

  describe("input schemas", () => {
    it("compiles as JSON Schema", () => {
      for (const { tool, where } of allTools()) {
        expect(() => ajv.compile(tool.inputSchema), where).not.toThrow();
      }
    });

    it("is an object schema whose required names are all declared properties", () => {
      for (const { tool, where } of allTools()) {
        expect(tool.inputSchema.type, where).toBe("object");
        for (const name of tool.inputSchema.required ?? []) {
          expect(Object.keys(tool.inputSchema.properties), `${where}.${name}`).toContain(name);
        }
      }
    });

    it("never marks a defaulted argument as required", () => {
      for (const { tool, where } of allTools()) {
        for (const name of tool.inputSchema.required ?? []) {
          expect(tool.inputSchema.properties[name], `${where}.${name}`).not.toHaveProperty("default");
        }
      }
    });

    it("carries the docstring text and literal defaults through", () => {
      const search = CONTRACTS.get("cellguide")!.tools.find((t) => t.name === "search_cell_types")!;
      expect(search.inputSchema.required).toEqual(["query"]);
      expect(String(search.inputSchema.properties.query.description)).toMatch(/Search query/);
      expect(search.inputSchema.properties.limit.default).toBe(10);
    });
  });

  describe("output schemas", () => {
    it("exists only for the five servers that ship schemas.json", () => {
      for (const { slug, tool, where } of allTools()) {
        if (SCHEMA_TIER.includes(slug)) continue;
        expect(tool.outputSchema, where).toBeUndefined();
      }
    });

    it("compiles as JSON Schema wherever it is present", () => {
      for (const { tool, where } of allTools()) {
        if (!tool.outputSchema) continue;
        expect(() => ajv.compile(tool.outputSchema!), where).not.toThrow();
      }
    });

    it("does not put prose returns on the schema tier", () => {
      for (const slug of SCHEMA_TIER) {
        for (const tool of CONTRACTS.get(slug)!.tools) {
          expect(tool.returns, `${slug}/${tool.name}`).toBeUndefined();
        }
      }
    });

    it("keeps the schemas.json provenance", () => {
      expect(CONTRACTS.get("pubmed")!.originalConnector).toBeTruthy();
    });

    it("records the prose return shape where the docstring documents one", () => {
      const openalex = CONTRACTS.get("literature")!.tools.find(
        (t) => t.name === "openalex_search_works",
      )!;
      expect(openalex.returns).toMatch(/^Returns/);
    });
  });

  describe("error contracts", () => {
    /**
     * The servers declare exactly two machine-checkable error codes:
     * `openalex_key_required` (mcp_literature) and `contact_email_required`
     * (mcp_variants). Everything else surfaces as a transport error.
     */
    it("declares only the two structured codes the servers return", () => {
      const codes = new Set<string>();
      for (const { tool } of allTools()) {
        for (const c of tool.errorCases ?? []) codes.add(c.case);
      }
      expect([...codes].sort()).toEqual(["contact_email_required", "openalex_key_required"]);
    });

    it("shapes each error case as the server returns it", () => {
      for (const { tool, where } of allTools()) {
        for (const c of tool.errorCases ?? []) {
          expect(c.expectedError, where).toEqual({ error: c.case, message: "string" });
        }
      }
    });

    it("gates every OpenAlex-backed literature tool on the API key", () => {
      const gated = CONTRACTS.get("literature")!
        .tools.filter((t) => t.name.startsWith("openalex_"))
        .map((t) => t.name);
      expect(gated.length).toBe(7);
      for (const name of gated) {
        const tool = CONTRACTS.get("literature")!.tools.find((t) => t.name === name)!;
        expect(tool.errorCases?.map((c) => c.case), name).toContain("openalex_key_required");
      }
    });

    it("leaves the keyless arXiv tools ungated", () => {
      for (const tool of CONTRACTS.get("literature")!.tools.filter((t) =>
        t.name.startsWith("arxiv_"),
      )) {
        expect(tool.errorCases, tool.name).toBeUndefined();
      }
    });

    it("gates exactly the NCBI variant tools that need a contact email", () => {
      const gated = CONTRACTS.get("variants")!
        .tools.filter((t) => t.errorCases?.some((c) => c.case === "contact_email_required"))
        .map((t) => t.name)
        .sort();
      expect(gated).toEqual([
        "clinvar_get_records",
        "clinvar_search",
        "clinvar_variant_by_rsid",
        "dbsnp_get_rsids",
        "dbsnp_search_by_region",
      ]);
    });
  });

  describe("upstream pacing", () => {
    it("derives requestsPerSecond from the declared interval", () => {
      for (const [slug, contract] of entries()) {
        for (const up of contract.upstreams ?? []) {
          expect(up.minIntervalSeconds, `${slug}/${up.package}`).toBeGreaterThan(0);
          expect(up.requestsPerSecond).toBeCloseTo(1 / up.minIntervalSeconds, 2);
        }
      }
    });

    it("only names upstream packages the tools actually reach, and that exist", () => {
      for (const [slug, contract] of entries()) {
        const reached = new Set(contract.tools.flatMap((t) => t.upstreams ?? []));
        for (const up of contract.upstreams ?? []) {
          expect(reached, `${slug}/${up.package}`).toContain(up.package);
          expect(existsSync(join(LIB_DIR, up.package, "client.py"))).toBe(true);
        }
      }
    });

    it("honours the documented politeness intervals", () => {
      const byPackage = (slug: string) =>
        new Map((CONTRACTS.get(slug)!.upstreams ?? []).map((u) => [u.package, u]));

      const literature = byPackage("literature");
      expect(literature.get("openalex_works")!.minIntervalSeconds).toBe(0.5);
      expect(literature.get("openalex_works")!.requestsPerSecond).toBeLessThanOrEqual(2);
      expect(literature.get("arxiv_fetch")!.minIntervalSeconds).toBe(3);
      expect(literature.get("arxiv_fetch")!.requestsPerSecond).toBeLessThanOrEqual(0.5);

      const variants = byPackage("variants");
      expect(variants.get("gnomad_variants")!.minIntervalSeconds).toBe(6);
      expect(variants.get("gnomad_variants")!.requestsPerSecond).toBeLessThan(1);
    });

    it("stays silent where the client is built at import time", () => {
      // mcp_cellguide and mcp_zinc construct their clients on import rather
      // than through a paced fleet helper, so no interval is derivable.
      expect(CONTRACTS.get("cellguide")!.upstreams).toBeUndefined();
      expect(CONTRACTS.get("zinc")!.upstreams).toBeUndefined();
    });
  });
});
