import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { WorkspaceTypertGenerator } from '../../deepseek-harness/packages/typert/generator/lib/types/workspace.js'

const root = resolve(import.meta.dirname, '../..')
const pluginsRoot = resolve(root, 'plugins')
const remotePackages = []

for (const entry of await readdir(pluginsRoot, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue
  const packageRoot = resolve(pluginsRoot, entry.name)
  const manifest = JSON.parse(await readFile(resolve(packageRoot, 'package.json'), 'utf8'))
  if (manifest.exports?.['./remote'] === undefined) {
    await removeTypertArtifacts(packageRoot)
    continue
  }
  const artifacts = new WorkspaceTypertGenerator(root, {
    packageRoots: ['deepseek-harness/packages', 'plugins', 'store'],
  }).generate([manifest.name], ['host'])
  const host = artifacts.find(artifact => artifact.face === 'host')
  if (host?.remote === undefined) throw new Error(`${manifest.name} exports ./remote but generated no Remote contribution.`)
  await mkdir(resolve(packageRoot, 'lib'), { recursive: true })
  await Promise.all([
    writeFile(resolve(packageRoot, 'lib/typert.host.js'), host.js),
    writeFile(resolve(packageRoot, 'lib/typert.host.d.ts'), host.dts),
    writeFile(resolve(packageRoot, 'lib/typert.remote-client.js'), host.remote.js),
    writeFile(resolve(packageRoot, 'lib/typert.remote-client.d.ts'), host.remote.dts),
    writeFile(resolve(packageRoot, 'lib/typert.remote-client.d.ts.map'), host.remote.dtsMap),
  ])
  remotePackages.push(manifest.name)
}

await writeRemoteAssembly(remotePackages.sort())
console.log(`Generated Typert contracts for ${remotePackages.length} ZeroWall remote plugins.`)

async function removeTypertArtifacts(packageRoot) {
  for (const name of [
    'typert.host.js', 'typert.host.d.ts', 'typert.remote-client.js',
    'typert.remote-client.d.ts', 'typert.remote-client.d.ts.map',
  ]) await rm(resolve(packageRoot, 'lib', name), { force: true })
}

async function writeRemoteAssembly(packages) {
  const imports = packages.map((name, index) => `import remote${index} from '${name}/remote'`)
  const values = packages.map((_name, index) => `remote${index}`)
  const source = [
    '// Generated by tools/plugins/generate-typert.mjs. Do not edit.',
    ...imports,
    '',
    `export const zerowallRemoteContributions = [${values.join(', ')}] as const`,
    '',
  ].join('\n')
  await writeFile(resolve(pluginsRoot, 'base/src/client/remote-contributions.generated.ts'), source)
}
